import React, { useState, useEffect } from 'react';
import { useRouter } from "next/router";
import PropTypes from "prop-types";

import Slider from "react-slick";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Link from 'next/link';
import Leaderboard from '../components/Ads/Leaderboard';


// components

const PrivacyPolicy = (props) => {

  const [playlists, setPlaylist] = useState(props.data);
  const [isloading, setisloading] = useState(false);



  return (
    <>

    


      <section class="text-gray-600 body-font bg-black">
        <div class="container px-5 py-20 mx-auto">
          <center>
            <Leaderboard />
          </center>
          <div className="flex flex-wrap mt-10">
          <div class="wpb_wrapper text-white">
            <h1>Privacy Policy</h1>
            <br/>
            <h2>About ARY Digital</h2>
            <br/>
            <p className="font-normal"><strong><a href="https://arydigital.tv">Arydigital.tv</a></strong>, is an online entertainment platform which brings you its very own official and original content of ARY Digital. We are the only site which offers official and original content from all your favorite shows of ARY Digital.</p>
            
            <br/>
            <p className="font-normal">The dramas to reality shows aired of <em>ARY Digital’s</em> channel everything is available on the website. Explore all this and more on our easily accessible site you can also watch the live transmission of <strong>ARY Digital</strong> on our website. Catch full episodes of all the shows you like at your convenience and you can also share it with your friends.</p>
            <br/>

           
            <h2>Privacy Policy</h2>
            <br/>
            <p className="font-normal">This privacy policy covers the information about ARY Digital; all the personal information of the users is collected if the users register with the website for any of the programs. The information is saved and only used for the registration purpose.</p>
            
            <br/>
            
            <h2>Terms and Conditions</h2>
            <br/>
            <p className="font-normal">This document is an electronic record in terms of information and rules that are applicable to the users. This electronic record is generated by a computer system and does not require any physical or digital signatures. This is a legal agreement between you, the user of the services of ARY Digital’s website. If you do not agree to these terms and conditions, you are not entitled to use the services of this website.</p>
            <br/>
            <p className="font-normal">By visiting the site or using any of the services of ARY Digital’s site you are agreeing to these terms and conditions. The content which is viewed on the ARY Digital’s website is copyrighted material of ARY Digital, and shall not be used by any other user without the permission of ARY Digital’s website.</p>
            <br/>
            <p className="font-normal">You acknowledge and agree not to either directly or indirectly use ARY Digital’s content from the website, whether it is in the form of video or text. The web-based service, or other means of content, should not be download, capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, transmit or retransmit the content or create any derivative work and/or material based on the content.</p>
            <br/>
            <p className="font-normal">You agree that your use of the website’s services and the content may give you the opportunity to view, share, post and comment in accordance with these terms and conditions. You agree that you will not misuse the content. In case if the site allows you to download or stream any of the contents therein, you agree that you will not use, sell, transfer or transmit the content to any person or upload the content on any other website, webpage or software.</p>
            <br/>
            <p className="font-normal">You may have an opportunity to publish, transmit, submit, or otherwise post only comments. You agree that ARY Digital shall have the right to unapproved any comment as needed. If you have any complaints relating to any material uploaded on the website, and then please contact: web@aryservices.com 
            Your email must have your name, with the details of the objectionable post.</p>

            <br/>

           
            <h2>Changes in Privacy Policy</h2>
            <br/>
            <p className="font-normal">From time to time we may update this privacy policy as needed.</p>
            <br/>
            <h2>Contact Us</h2>
            <br/>
            <p className="font-normal">If you have any questions about this privacy policy, or any other inquiry, you can contact us at web@aryservices.com.</p>
            </div>
          </div>
        </div>
      </section>







    </>
  );
}



export default PrivacyPolicy;